services:
  back:
    image: zucchiattievalback
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back_container_zucchiatti

    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    volumes:
      - ./back/dev.db:/app/dev.db
    command: ["sh", "-c", "npx prisma migrate deploy && node server.js"]
    networks:
      - app_network

  front:
    image: zucchiattievalfront
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://nszucchiattievanbceqxgdg-container-back-zucchiatti.functions.fnc.fr-par.scw.cloud"
    container_name: front_container_zucchiatti
    ports:
      - "8080:80"
    depends_on:
      - back
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
